### ISSUE TITLE
More in depth example or tutorial in readme

### ISSUE THREAD

**Issue by damwhit** [algolia/algoliasearch-alexa#7]
I think that it would be incredibly helpful to have a more in depth tutorial or example on how to integrate algolia with an alexa still.  

I am very new to lambda and alexa, and find the docs lacking detail on how exactly to get this up and running with a skill.

It is unclear what additional code is needed to allow the code in the readme to sync up with an Alexa skill.  Would really appreciate something more in depth.  Thanks!

**Comment by damwhit** [comment]
Have been trying to get at least a response back when testing my alexa skill, but it will only return undefined.  My lambda function is below.  Do I need to hook this up with alexa-sdk to get a proper response?
```
const algoliaAlexaAdapter = require('algoliasearch-alexa');
const findVolunteerProject = algoliaAlexaAdapter({
  algoliaAppId: 'id',
  algoliaApiKey: 'key',
  defaultIndexName: 'index',
  handlers: {
    'GetNewProjectIntent': {
      answerWith: function (data) {
        if(data.results.length) {
          this.emit(':tell', `There were ${data.results.hits.length} products found.`);
        } else {
          this.emit(':tell', 'We could find no products. Please try again.');
        }
      },
    },
  },
});

module.exports = findVolunteerProject;
```

**Comment by dustincoates** [comment]
@damwhit Completely agree that we need to have a more in-depth tutorial! Once we fill this out more it's top of the list to complete.

In the meantime, here's a non-Algolia specific that goes into some detail on getting everything set up around Alexa and Lambda: http://tobuildsomething.com/2015/08/14/Amazon-Echo-Alexa-Tutorial-The-Definitive-Guide-to-Coding-an-Alexa-Skill/.

Thanks as well for the follow-up. A few questions that can help us figure out what's going on:
- Are you testing within Lambda or via Alexa (e.g. speaking to the device)?
- If testing within Lambda, can you share the test request?
- What does your intent schema look like?

If you're up for it, I would love to have an on hands video + screen sharing call so we can sort this out together. Won't take long and would be a very good feedback for me as the author.

Also&mdash;thank you so much for being one of the early users of the adapter. :) How did you come across it?

**Comment by damwhit** [comment]
@dustincoates I really appreciate the quick response!  Thanks for passing along the alexa skill tutorial too!

* I am testing via the Alexa service simulator.
* Intent schema is: 
```
{
  "intents": [
    {
      "intent": "GetNewProjectIntent"
    },
    {
      "intent": "AMAZON.HelpIntent"
    },
    {
      "intent": "AMAZON.StopIntent"
    },
    {
      "intent": "AMAZON.CancelIntent"
    }
  ]
```

I would love to do a screen share with you to help figure this out!  Really appreciate you going out of your way.  When is a good time for you?

I came across the adapter because I am trying to build an algolia backed alexa skill that can tell folks a random volunteer opportunity from an index of volunteer opportunities.

**Comment by dustincoates** [comment]
@damwhit Can you send me an email at dustin@algolia.com? We'll schedule a time for a screenshare.
